### ISSUE TITLE
New releases?

### ISSUE THREAD

**Issue by preco21** [babel/eslint-plugin-babel#114]
Hello, guys.

Since the [`no-invalid-this` issue](https://github.com/babel/eslint-plugin-babel/issues/12) has been fixed, I really hope to use of the rule which is very useful feature for class properties user.

It could only be a my opinion, but still I think this is enough to make new minor release to add the feature.

How do you think about it?

**Comment by hzoo** [comment]
I was removing the changes but it's using const and all that so I guess we'll just do a major

**Comment by preco21** [comment]
@hzoo Awesome! :tada:
