### ISSUE TITLE
Deprecate no-await-in-loop

### ISSUE THREAD

**Issue by nmote** [babel/eslint-plugin-babel#116]
Since ESLint now supports async/await, they agreed to take `no-await-in-loop` and my [pull request](https://github.com/eslint/eslint/pull/7563) to add it has just been merged.

Therefore, after the next ESLint release, I think it would be appropriate to deprecate the copy of the rule in this plugin and after some period of time, remove it altogether.

Please let me know how you would like to go about this, and I'll be happy to put up pull requests.

**Comment by hzoo** [comment]
Sorry didn't see this - whenver ESLint itself has the rule we can definetely deprecate it..

Should just follow the same format https://github.com/babel/eslint-plugin-babel/pull/119
