### ISSUE TITLE
Added deprecated flag to rule meta object

### ISSUE THREAD

**Issue by wagerfield** [babel/eslint-plugin-babel#118]
Please add the `deprecated` flag to the `meta` object for all deprecated rules. 

This is the documented way of declaring a rule as being deprecated.

http://eslint.org/docs/developer-guide/working-with-rules#rule-basics

```
module.exports = {
  meta: {
    deprecated: true
  },
  create: function() {
    ...
  }
}
```

**Comment by hzoo** [comment]
Do you want to make a pr for this?

**Comment by wagerfield** [comment]
Sure thing.
