### ISSUE TITLE
`no-invalid-this` with ES7 class properties

### ISSUE THREAD

**Issue by hzoo** [babel/eslint-plugin-babel#12]
``` js
class {
    toggleLocationActiveState = () => {
        this.props.onActivateLocation(this.props.id);
    }
}
```

```
curiosity:foo gajus$ eslint -v
v1.2.1
```

```
/foo/index.js
  13:9   error  Unexpected `this`                       no-invalid-this
  13:39  error  Unexpected `this`                       no-invalid-this
```

Ref https://github.com/babel/babel-eslint/issues/173 @gajus

**Comment by ssorallen** [comment]
How cutting edge does this plugin strive to be? Class instance fields are still in stage 1 proposal.

**Comment by hzoo** [comment]
Whatever babel-eslint supports so stage-0 I suppose

**Comment by philostler** [comment]
So what's the status of this? This is really creating a lot of noise in my linting atm

**Comment by jquense** [comment]
@philostler PR's accepted :)

**Comment by philostler** [comment]
@jquense I would if I knew where to start. The eslint plugins are alien territory to me

**Comment by gcedo** [comment]
+1

**Comment by wmill** [comment]
+1

**Comment by mathieumg** [comment]
I implemented a very basic version in https://github.com/babel/eslint-plugin-babel/issues/101 if people want to try it and give feedback, thanks!
