### ISSUE TITLE
new-cap does not support disabling check on properties

### ISSUE THREAD

**Issue by nkovacs** [babel/eslint-plugin-babel#124]
Eslint's new-cap has an option to disable the check on object properties: https://github.com/eslint/eslint/commit/4222799f742b16a8ed18c0bc13f6c143622c732f

This is missing from this plugin's new-cap.

**Comment by kentcdodds** [comment]
Thanks for reporting. Would you like to contribute a fix? Let us know how we can enable you to do that.

**Comment by existentialism** [comment]
As mentioned in the PR, this is now fixed as of 5.0.
