### ISSUE TITLE
Request: Extend `arrow-spacing` rule to support class properties #9516

### ISSUE THREAD

**Issue by EvHaus** [babel/eslint-plugin-babel#132]
As per recommendation from https://github.com/eslint/eslint/issues/9516#issuecomment-339380128, I was wondering if `eslint-plugin-babel` would consider extending the [`arrow-spacing` rule](https://eslint.org/docs/rules/arrow-spacing) to support class property functions. For example:

The following rule: `"arrow-spacing": ["error", {"before": true, "after": true}` should result in this change:

```js
// Before
class Test {
    test=()=>{ }
}

// After
class Test {
    test = () => { }
}
```

However, at the moment, the `arrow-spacing` seems to ignore class properties entirely. Is there any reason NOT to update the rule to support class properties?

<details>
<summary>Environment</summary>
**Tell us about your environment**

* **ESLint Version:** 4.9.0
* **Node Version:** 8.8.0
* **npm Version:** 5.4.2

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint
</details>

<details>
<summary>Configuration</summary>

```js
{
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 2017,
        "sourceType": "module"
    },
    "rules": {
        "arrow-spacing": ["error", {"before": true, "after": true}]
    }
}
```
</details>

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
