### ISSUE TITLE
require-jsdoc

### ISSUE THREAD

**Issue by grydstedt** [babel/eslint-plugin-babel#136]
The require-jsdoc rule does not detect fat arrow functions inside classes (via babel) when warning about missing comments. Is that something that this plugin could augment?

**Comment by lightninglu10** [comment]
+1, any movement here?

**Comment by scythargon** [comment]
+1 or give me any clues and I'll create a PR please

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
