### ISSUE TITLE
Missing non existing class parameter 'k'

### ISSUE THREAD

**Issue by Zydnar** [babel/eslint-plugin-babel#148]
Tell us about your environment

    ESLint Version: 4.19.1
    Node Version: 9.0.0
    npm Version: 5.5.1

What parser (default, Babel-ESLint, etc.) are you using?
eslint + babel-eslint+ WebStorm

Please show your full configuration:
https://pastebin.com/yzCgfgEQ
Code:
https://pastebin.com/0mzMg0SE

What did you expect to happen?
Error should throw at the "x" function, not at the top of class.

What actually happened? Please include the actual, raw output from ESLint.
Error throws at the beginning of class JSDoc and filling there `@param {Number} k - foo` makes error disappear. Filling out JSDoc for function "x" with same text works too, but error is being shown in wrong place.

**Comment by Zydnar** [comment]
There (Eslint issue tracker) I was said to report issue here :D Anyway, I hope this help you make it better.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
