### ISSUE TITLE
Request: extend ESLint's `valid-typeof` rule to accept "bigint" as a valid comparison value

### ISSUE THREAD

**Issue by fmartin5** [babel/eslint-plugin-babel#153]
Some people are starting to use `typeof` with `"bigint"` in their code, but ESLint's `valid-typeof` rule does not accept it, and ESLint will not support it until the proposal for BigInt reaches stage 4 (it's currently in stage 3).

Then someone at ESLint [suggested](https://github.com/eslint/eslint/pull/9636#issuecomment-381019896) to check eslint-plugin-babel for an augmented rule:
> Your best chance at this point is to use babel-eslint (to parse literals), as well as to see if there is a rule in eslint-plugin-babel which augments valid-typeof to support big integers.

**Comment by GeneralYouri** [comment]
Seconded, it's annoying to have to disable rules or go through other loop holes just to be able to work with `BigInt`s.

The 'no-undef' rule can be bypassed by adding `BigInt` to ESLint globals, which stops it from reporting the use of the `BigInt` constructor, which is a reasonable workaround. But for the 'valid-typeof' rule I don't see a workaround other than disabling this rule either globally or locally, which really sucks either way.

I'd easily use eslint-plugin-babel even if all it did was augment that one rule for me.
