### ISSUE TITLE
Deprecate babel/quotes since it's fixed in ESLint 5

### ISSUE THREAD

**Issue by edmorley** [babel/eslint-plugin-babel#154]
Hi!

The `babel/quotes` rule references the upstream ESLint issue that it is meant to fix, here:
https://github.com/babel/eslint-plugin-babel/blob/e5656708471d5417a36549c4070a4e242741fd24/rules/quotes.js#L10-L14

Looking at eslint/eslint#9662, it has been fixed by eslint/eslint#9664, which is included in ESLint 5.0.

As such, I believe the `babel/quotes` rule can now be deprecated.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
