### ISSUE TITLE
How to get class properties to stop throwing?

### ISSUE THREAD

**Issue by corysimmons** [babel/eslint-plugin-babel#156]
I was getting class property errors in ESLint so I Googled "eslint class properties", landed on https://npm.im/eslint-plugin-class-property which said:

>Please use babel-plugin-eslint with the babel/semi rule!

So I did, and I'm still getting ESLint errors on class properties. What am I doing wrong?

`npm i eslint-plugin-babel`

```js
// package.json
"eslintConfig": {
  "plugins": ["babel"],
  "rules": {
    "babel/semi": 0
  }
}
```

```js
class FooComponent {
  state = { // throws on the equal sign
    a: 1
  }
}
```

Thank you.

**Comment by ljharb** [comment]
you need the babel-eslint *parser*, the plugin is just for rules.

**Comment by corysimmons** [comment]
Oh thanks @ljharb 👌

**Comment by kfprimm** [comment]
https://github.com/babel/babel-eslint#setup
