### ISSUE TITLE
curly spacing and defaultMember and members on one line

### ISSUE THREAD

**Issue by kusera** [babel/eslint-plugin-babel#16]
The `object-curly-spacing` rule doesn't seem to apply to objects that are in the second half of a hybrid import statement like:

`import React, {Component, PropTypes} from 'react';`

Is there any way to get the plugin to mark these kinds of objects? Or do I have to put the members object on its own line?

**Comment by jquense** [comment]
imports aren't objects so I think it makes sense that the rule doesn't apply in this case.

**Comment by kusera** [comment]
That does make sense, but this the linter will complain at this line:

`import {Component, PropTypes} from 'react';`

It's not a big deal but the inconsistency is jarring.

**Comment by hzoo** [comment]
Shouldn't be an issue anymore, otherwise a bug since this would just be something eslint itself handles (since it's es2015)
