### ISSUE TITLE
Private methods (parser plugin 'classPrivateMethods')

### ISSUE THREAD

**Issue by andrewmiller1** [babel/eslint-plugin-babel#166]
Private variables work but not private methods. Works with babel. In my babel config I have the plugin mentioned.

```
Parsing error: This experimental syntax requires enabling the parser plugin: 'classPrivateMethods'
```

```js
class myClass {
  #myMethod() {
  }
}
```

Let me know if you need any logs

**Comment by hadnet** [comment]
I resolved that problem adding in .eslintrc `"extends": [
        "plugin:eslint-plugin/classPrivateMethods"
    ],`

I'm using:
"babel-eslint": "^10.0.1",
"eslint": "^5.13.0"

**Comment by 1nfility** [comment]
Same error

**Comment by Scrum** [comment]
@hzoo Is there any movement to solve this problem?

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
