### ISSUE TITLE
Adjust test matrix

### ISSUE THREAD

**Issue by existentialism** [babel/eslint-plugin-babel#167]
From @edmorley in https://github.com/babel/eslint-plugin-babel/pull/152

> Though I guess Node 4 support could be kept (avoiding the need for a major version bump here), but the test matix adjusted such that only ESLint 4 was tested on Node 4, and not ESLint 5.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
