### ISSUE TITLE
`padded-blocks` with decorators

### ISSUE THREAD

**Issue by fanatid** [babel/eslint-plugin-babel#17]
packages:

```
npm ls --depth=0
...
├── babel-eslint@4.1.3
├── eslint@1.5.1
├── eslint-config-standard@4.4.0
├── eslint-plugin-standard@1.3.1
...
```

code:

``` js
let a = function () {}

let b = function () {
  @a
  class X {
    constructor () {}
  }

  return new X()
}

b()
```

error:

```
3:21  error  Block must not be padded by blank lines  padded-blocks
```

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
