### ISSUE TITLE
Use prettier?

### ISSUE THREAD

**Issue by Graham42** [babel/eslint-plugin-babel#172]
Would you be open to using [Prettier](https://prettier.io/)? Auto-formatting is amazing. If so I can open a PR.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
