### ISSUE TITLE
there is no rules for properties indent.

### ISSUE THREAD

**Issue by ldwqh0** [babel/eslint-plugin-babel#179]
There is my code
```javascript
export default class Good {
            test () {

            }
                 a=1
    a=2
    ad () {

    }
}
```
The line at "a=1" is not good .

![图片](https://user-images.githubusercontent.com/9332016/60633648-4851eb80-9e3e-11e9-8b5c-e1df4781476a.png)

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
