### ISSUE TITLE
babel/no-invalid-this does not recognize private properties

### ISSUE THREAD

**Issue by fergald** [babel/eslint-plugin-babel#182]
E.g. if index.mjs contains

```js
export class Foo extends HTMLElement {
  foo = this.ok();
  ok = () => {
    return this.ok;
  }
  #notOk = () => {
    return this.#notOk;
  }
}
```

then eslint with the babel plugin will complain about the second `this` but not the first

```
$@ ./node_modules/.bin/eslint  invalid.mjs

/home/fergal/nodejs/invalid.mjs
  7:12  error  Unexpected 'this'  babel/no-invalid-this

✖ 1 problem (1 error, 0 warnings)


```

**Comment by fergald** [comment]
Slightly better example

```js
export class Foo extends HTMLElement {
  foo = this.ok();
  #foo = this.ok();
  ok = () => {
    return this.ok;
  }
  #notOk = () => {
    return this.#notOk;
  }
}
```

because that complains about both of the privates and neither of the publics.

```
  3:10  error  Unexpected 'this'  babel/no-invalid-this
  8:12  error  Unexpected 'this'  babel/no-invalid-this
```

**Comment by fergald** [comment]
Looks like this just needs a tweak to

https://github.com/babel/eslint-plugin-babel/blob/e5656708471d5417a36549c4070a4e242741fd24/rules/no-invalid-this.js

to make line 14

            if (node.type === "ClassProperty" || node.type === "ClassPrivateProperty") {

**Comment by jimblue** [comment]
Hello,
I don't understand why I getting the same warning since the fix have been merge ?
Does anyone else still having this issue like me ?
