### ISSUE TITLE
camelcase support "allow" pattern option from eslint base

### ISSUE THREAD

**Issue by TSMMark** [babel/eslint-plugin-babel#186]
https://eslint.org/docs/rules/camelcase#allow

Original test cases from eslint:

https://github.com/eslint/eslint/blob/41b1e4308c1cb01c8b00cc8adc36440e77854117/tests/lib/rules/camelcase.js#L200-L215

https://github.com/eslint/eslint/blob/41b1e4308c1cb01c8b00cc8adc36440e77854117/tests/lib/rules/camelcase.js#L687-L706

I think I can take a stab at PR today

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
