### ISSUE TITLE
As of latest ESLint, `babel/valid-typeof` is no more needed

### ISSUE THREAD

**Issue by miyaokamarina** [babel/eslint-plugin-babel#188]
At least in version 6.7.2, ESLint supports the `'bigint'` type out of the box: [source](https://github.com/eslint/eslint/blame/e4ab0531c4e44c23494c6a802aa2329d15ac90e5/lib/rules/valid-typeof.js#L42), so the rule may be deprecated in future versions of this plugin.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
