### ISSUE TITLE
Proposed rule: no-await-in-loop

### ISSUE THREAD

**Issue by nmote** [babel/eslint-plugin-babel#20]
I proposed this rule in an [issue on eslint](https://github.com/eslint/eslint/issues/4166), but it was closed because they do not support experimental features.

This plugin says that it contains replacements to core ESLint rules. Would you relax that requirement and allow entirely new rules? If not, is there any place where a rule for ES7 would belong?

**Comment by hzoo** [comment]
Yeah that's totally fine (I linked you here) - we can change the readme to reflect that too

**Comment by hzoo** [comment]
None of the rules are written in es6 so you'll have to convert it or change how we export the rules

**Comment by jquense** [comment]
I feel fine taking the rule, tho you'd have to either introduce a build step or rewrite it as es5 :P

**Comment by nmote** [comment]
Cool, I'm happy to rewrite as ES5. Although I hear there are some good transpilers out there :stuck_out_tongue: I'll put up a PR with tests.

**Comment by hzoo** [comment]
If you want to make a PR with a build step that's fine too but probably more work

**Comment by nmote** [comment]
I'll consider it but to be honest I'm unlikely to actually get to it
