### ISSUE TITLE
Add a decorator-undef-shorthand-prop rule.

### ISSUE THREAD

**Issue by martndemus** [babel/eslint-plugin-babel#26]
The following is a nice idiom using decorators:

``` javascript
var Person = Model.extend({
  @attr firstName,
  @attr lastName
});
```

But eslint will then warn: `error: "firstName" is not defined. (no-undef)`.

So it might be a good case to add a rule that allows this.

**Comment by hzoo** [comment]
Oh I thought we discussed that it would be invalid (the error is correct)?

**Comment by martndemus** [comment]
The error is correct, but the code is also valid. I thought it would be better to add a rule that consciously enables you to use this idiom. Just like you can enable some exceptions on `eqeqeq` with the `smart` option.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
