### ISSUE TITLE
Bump babel-eslint version (5.0.0-beta)

### ISSUE THREAD

**Issue by dan-santana** [babel/eslint-plugin-babel#33]
Could you release a version using the `babel-eslint` 5.0.0-beta? It is needed when using babel 6.

**Comment by hzoo** [comment]
Not sure what you mean by this? You should be able to just update that yourself?

**Comment by dan-santana** [comment]
I'm sorry, my fault. I saw the package.json and found the `babel-eslint` as dependency, but actually it's only a dev dependency.

Anyways, shouldn't `babel-eslint` be on `peerDependencies`?

**Comment by hzoo** [comment]
Yeah I suppose but people using this have to use babel-eslint for it to work - I don't think we need eslint as a peer dependency either

**Comment by dan-santana** [comment]
Hmm maybe with `babel-eslint` in `peerDependencies` it would be clearer that this plugin doesn't change the parser (as I  initially thought), and that you have to add it manually (actually I don't even know if a plugin can do any config modification like this)... but as far as I can see I didn't find any eslint plugin specifying anything as `peerDependencies`... maybe I'm just overthinking.

Anyway, thank you!

**Comment by hzoo** [comment]
yep! Yeah this actually only adds rules (in the readme it says "An eslint plugin companion to babel-eslint.")
