### ISSUE TITLE
Implement auto fix functionality for object-curly-spacing rule eslint/eslint#3857

### ISSUE THREAD

**Issue by zaygraveyard** [babel/eslint-plugin-babel#37]
Ref eslint/eslint#3857

**Comment by jquense** [comment]
Are plugins supposed to implement autofixes? I support that makes sense, but I think thats going to be out of scope for this plugin...unless you want to write a PR for it :)

**Comment by zaygraveyard** [comment]
> Are plugins supposed to implement autofixes?

I'd says yes since the rule this plugin is replacing do so.

> unless you want to write a PR for it :)

I already am writing it ^^
