### ISSUE TITLE
Rule Suggestion: Require semicolon after class static properties

### ISSUE THREAD

**Issue by IanVS** [babel/eslint-plugin-babel#43]
Static class properties require a semicolon, as pointed out in https://phabricator.babeljs.io/T6873.  Babel is now bombing with a compilation error if it doesn't find a semicolon.  It would be super beneficial to have a linting rule to catch this.

**Comment by oztune** [comment]
+1

**Comment by hzoo** [comment]
We're goina revert to previous behavior since they discussed this more in https://github.com/jeffmo/es-class-fields-and-static-properties/issues/26#issuecomment-177720642

https://github.com/babel/babel/pull/3332

**Comment by IanVS** [comment]
Might still be nice to have a linting rule to enforce them, yes?

**Comment by hzoo** [comment]
Yeah, either way yes for users that wan't semicolons

**Comment by Download** [comment]
> We're goina revert to previous behavior 

Thanks!!! I hated having to add semicolons to all my source files! ... not sure if I'm going to revert them all but at least I can write the 'cleaner' semicolon-less version again now. Yay!!

**Comment by IanVS** [comment]
@Download, off-topic for this issue, but if you want to remove them, you can probably use ESLint's `--fix`

**Comment by GlamCat** [comment]
Do we still haven't got such a rule? Would be nice to have one.

+1

**Comment by mjrussell** [comment]
This would still be a great feature (both static and regular class properties) for those who enforce JS with semicolons.

+1

**Comment by jquense** [comment]
so the only way such a rule would make sense here is as an extension of the builtin semi rule that last enforces them in this case. if anyone wants to PR that I'd happily accept

**Comment by jeffshaver** [comment]
Would also like the option to disallow them unless necessary.

**Comment by elodszopos** [comment]
Hey guys, kind of an old thread. Anything going on with this one? Would be amazing to have this.

**Comment by r3nya** [comment]
Yeah! @elodszopos +1
