### ISSUE TITLE
eslint 2.0.0 support

### ISSUE THREAD

**Issue by idolize** [babel/eslint-plugin-babel#51]
Right now the peerDependency for eslint is still in the 1.x.x version and npm complains:

```
npm ERR! peerinvalid The package eslint@2.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-babel@3.1.0 wants eslint@>=1.0.0
```

What needs to be done to support the latest eslint?

Thanks for all the great work!

**Comment by klimashkin** [comment]
Because babel-eslint still don't support eslint 2
https://github.com/babel/babel-eslint/issues/254

**Comment by wmertens** [comment]
@klimashkin that issue is now closed, babel-eslint supports eslint 2

**Comment by hzoo** [comment]
This is still an issue?
