### ISSUE TITLE
Infix spacing for static class properties

### ISSUE THREAD

**Issue by IanVS** [babel/eslint-plugin-babel#58]
ESLint's `space-infix-ops` will catch:

```
/*eslint space-infix-ops: "error"*/

var a =2;
```

But, it won't catch a static property assignment:

```
/*eslint space-infix-ops: "error"*/

export class foo {
    static a =2;
}
```

I'd like to propose an extension to the `space-infix-ops` rule which would enforce spacing around assignment operators of static class properties.

**Comment by HQidea** [comment]
any progress?

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
