### ISSUE TITLE
no-duplicate-imports rule for Flow type imports

### ISSUE THREAD

**Issue by elliottsj** [babel/eslint-plugin-babel#59]
eslint's [no-duplicate-imports](http://eslint.org/docs/rules/no-duplicate-imports) rule does not differentiate between `import` and `import type` statements, and babel-eslint alone cannot do anything about it: https://github.com/babel/babel-eslint/issues/293

Perhaps we need a `babel/no-duplicate-imports` rule as part of this plugin which correctly handles the case when there's an `import` and `import type` statement for the same module?

**Comment by benmosher** [comment]
FYI, `import/no-duplicates` supports Flow imports.

**Comment by elliottsj** [comment]
Thanks @benmosher, works for me!

Though I do feel that Flow users shouldn't need to depend on eslint-plugin-import if they're already using eslint-plugin-babel. If eslint-plugin-babel aims to provide Babel-compatible equivalents to core ESLint rules, it should provide one for the core [`no-duplicate-imports`](http://eslint.org/docs/rules/no-duplicate-imports)

**Comment by lll000111** [comment]
@elliottsj I don't need a/the Babel plugin to use Flow. I have plugin-flowtype.

eslint should not complain about `import type`, but it still does!

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
