### ISSUE TITLE
async / await

### ISSUE THREAD

**Issue by josebalius** [babel/eslint-plugin-babel#6]
Do I need this plugin to use async await with eslint? I can't seem to get it to work.

**Comment by jquense** [comment]
not quite sure I understand the question. is there a specific eslint rule that isn't working with async/await?

**Comment by josebalius** [comment]
Sorry, I am not sure of the error I am getting.

I have a function in a class like this

```
class MyClass {
   async getFeed() {
       let articles = await db.getArticles();
   }
}
```

And I keep getting 

`error: undefined - Unexpected token` right where await is at.

So I guess I was just asking if this was the right place to get that functionality working?

**Comment by bgw** [comment]
I've been using babel-eslint with async/await on a personal project with no problems. Have you made sure that you [enabled the transformer in your `.babelrc`](http://babeljs.io/docs/advanced/transformers/)? Babel will give a parse error without it, as it's not enabled by default.

**Comment by thejameskyle** [comment]
It's probably better to ask these sort of questions in the Babel Slack: http://slack.babeljs.io

**Comment by jquense** [comment]
Ya I think your question is about using  Babel in general not this plugin. I would check out the Babel slack

**Comment by hzoo** [comment]
Yeah ESLint doesn't support experimental syntax (an exception for object rest/spread for React)

**Comment by crashbell** [comment]
that means my code below won't pass ESLint even with babel plugin:

```js
class Foo {
  asyn Bar() {
    const vars = await method()
    return vars
  }
}
```

Please correct me if I'm wrong. So far I got the error: 
`Unexpected space after *`

**Comment by austinmao** [comment]
+1 I am getting `Parsing error: Unexpected identifier`

Here is my .eslintrc:

```
{ "extends": "eslint-config-airbnb",
  "env": {
    "browser": false,
    "node": true,
    "mocha": true
  },
  "rules": {
    "react/no-multi-comp": 0,
    "import/default": 0,
    "import/no-duplicates": 0,
    "import/named": 0,
    "import/namespace": 0,
    "import/no-unresolved": 0,
    "import/no-named-as-default": 2,
    "comma-dangle": 0,  // not sure why airbnb turned this on. gross!
    "indent": [2, 2, {"SwitchCase": 1}],
    "no-console": 0,
    "no-alert": 0,
    "semi": 0,
    "id-length": 0,
    "no-multi-spaces": 2,
    "generator-star-spacing": 2,
    "babel/generator-star-spacing": 1,
    "babel/object-curly-spacing": 0,
    "babel/object-shorthand": 1,
    "babel/arrow-parens": 0,
    "babel/no-await-in-loop": 1
  },
  "plugins": [
    "react", "import", "babel"
  ],
  "settings": {
    "import/parser": "babel-eslint",
    "import/resolve": {
      moduleDirectory: ["node_modules", "src"]
    }
  },
  "globals": {}
}
```

and my .babelrc:

```
{
  "ignore": [
    "node_modules",
    "bower_components"
  ],
  "presets": ["es2015"],
  "plugins": [
    "syntax-async-functions",
    "transform-regenerator"
  ]
}
```
