### ISSUE TITLE
object-shorthand doesn't allow optional parameters

### ISSUE THREAD

**Issue by mhagmajer** [babel/eslint-plugin-babel#63]
The configuration below raises "Configuration invalid" errors.

``` js
    'babel/object-shorthand': [2, 'always', {
      ignoreConstructors: false,
      avoidQuotes: true,
    }],
```

**Comment by danez** [comment]
The rule in this repository is based on an older version of the original object-shorthand rule. This means that the 3rd config param in the array is not supported, only `'babel/object-shorthand': [2, 'always']` should work currently.

**Comment by hzoo** [comment]
deprecating those rules so closing https://github.com/babel/eslint-plugin-babel/pull/115
