### ISSUE TITLE
no async without await 

### ISSUE THREAD

**Issue by xjamundx** [babel/eslint-plugin-babel#77]
I'm new to async await and find myself declaring functions as `async` but forgetting to `await` the promises inside of them (instead just calling `let x = getData()` or whatever. Would it make sense to have a rule that warned when you created an `async` function put didn't `await` inside that function? 

I know you technically don't need `await` to use `async`, but might help some folks? Thoughts?

**Comment by hzoo** [comment]
I guess this could be suggested in eslint core now - unless we decide not to do so then we can do it here instead

**Comment by xjamundx** [comment]
Yeah it's probably an uneccessary rule anyway
