### ISSUE TITLE
Have individual documentation pages for each rule

### ISSUE THREAD

**Issue by jfmengels** [babel/eslint-plugin-babel#92]
Hi all!

I'm a maintainer of [`eslint-rule-documentation`](https://github.com/jfmengels/eslint-rule-documentation) which is a tool that associates ESLint plugin rule names to the url of the rule's documentation page. This allows other tools ([Atom's ESLint linter](https://github.com/AtomLinter/linter-eslint), [Atom's XO linter](https://github.com/sindresorhus/atom-linter-xo), [`eslint-find-rules`](https://github.com/sarbbottam/eslint-find-rules)) to link to it easily, in linting errors for instance. This allows users to find the documentation page for a rule and read it to better understand why the error has been reported or learn how to configure it more to their needs.

![image](https://cloud.githubusercontent.com/assets/3869412/18036610/a4abc3a4-6d6f-11e6-9eaf-d6e57d43fc57.png)

In this example, `import/no-extraneous-dependencies` is a link that redirects to https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md.

To provide a better experience to the users, `eslint-rule-documentation` should in my opinion link to an individual documentation page, where the rule is described in a bit of detail (reasoning, how it works, valid and invalid examples, when not to use it...). That is the case for ESLint core rules, and for many ESLint plugins. It is unfortunately not the case of this plugin, and would therefore request that you consider making this change. The standard way of doing things (advocated by the ESLint team) is to have individual markdown files located at `docs/rules/<rulename>.md`.

In the case of the rules copying and improving the behavior of core ESLint rules, I would recommend a simple file that would link to the original rule and describe why it should be used instead of the core ESLint rule.
For custom rules, something that looks like [this](https://github.com/eslint/eslint/blob/master/docs/rules/no-var.md) or [that](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md) would be awesome.

We have to manually add support for each ESLint plugin in `eslint-rule-documentation` to create links correctly ([see what it looks like](https://github.com/jfmengels/eslint-rule-documentation/blob/master/plugins.json)), and would prefer waiting to add support for this plugin until you have either refused, or agreed and implemented the change. I could provide help for this, but I would only do the grunt work, as I'm not accustomed to the rules to be able to explain the rationale for each.

Thank you for considering this, and of course, thank you all for your hard work on Babel and the plugin, they're awesome!

**Comment by hzoo** [comment]
The idea for the repo was a hack since we just replace the eslint rule at a point in time so didn't really think about documentation at the time. I'm in favor of doing it, but would ask for some help in adding it though.

> In the case of the rules copying and improving the behavior of core ESLint rules, I would recommend a simple file that would link to the original rule and describe why it should be used instead of the core ESLint rule.

That sounds good because it would be the same thing except to account for some other case.

**Comment by jfmengels** [comment]
> I'm in favor of doing it, but would ask for some help in adding it though

I can provide guidance and/or do the grunt work if you want. Just let me know. For the rationale behind the rules, I would then let you fill the gaps.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
